library('ograph')
ograph::initOGraph('HDO')
g<-new("ontGraph",ontology='HDO')
#graph=subGraphByNodes(g@graph,c('DOID:10652'))
#graph=subGraphByLevel(graph,l=3)
graph=mapGene2Graph(g@graph,file=system.file("extdata/annotation","human_g2d.txt", package ="topOnto"))
sink('/home/xin/Desktop/dd.txt')
calculate.upper.adj.matrix.print(graph)
sink()
